---
title: Nowcasting demo
output: 
  html_document:
    code_folding: hide
---

```{r}
library(dplyr)
library(ggplot2)

# read in data
df = read.csv("nowcast_demo_data.csv")

# filter to date range
start_date = as.Date("2020-11-15")
end_date = as.Date("2021-02-08")
df = df %>% 
  mutate(time=as.Date(time)) %>%
  filter(time >= start_date & time <= end_date) 

# select arbitrary timepoint
kernel = read.csv("kernel_2020-11-15.csv")
mid_case_date = as.Date("2020-11-15")
med = max(which(cumsum(kernel) <= 0.5))
mid_infect_date = mid_case_date + med

# add weights values to df
n_kernel = nrow(kernel)
n_left_kernel = med
n_right_kernel = n_kernel - med
rescale = 300 # rescale by factor of 300 to make visible on plot
df$kernel = c(rep(NA, as.numeric(mid_infect_date - start_date) - n_left_kernel),
              kernel$X0 * rescale,
              rep(NA, as.numeric(end_date - mid_infect_date) - n_right_kernel + 1)
              ) 
```

```{r}
# ggplot colors
ggplot_colors = c("#FC4E07", "#00AFBB", "#C77CFF", "#084885", "magenta")
case_color = "gray"
final_infections_color = "black"
infections_color = "#F8766D"
unstable_color= "#00BFC4"
kernel_color = "#C77CFF"
average_nowcast_color = "#7CAE00"
d = 11

# https://community.rstudio.com/t/scale-x-date-date-breaks-1st-and-15th-of-the-month/906/2
library(lubridate)
bimonthly <- function(x) {
  x_range <- range(x, na.rm = TRUE)
  date_range <- c(
    floor_date(x_range[1], "month"),
    ceiling_date(x_range[2], "month")
  )
  monthly <- seq(date_range[1], date_range[2], by = "1 month")
  sort(c(monthly, monthly + days(14)))
}

i = which(!is.na(df$kernel))
ggplot(df) +
  geom_rect(data=data.frame(), aes(xmin=max(df$time)-d+1, xmax=max(df$time), 
                                   ymin=0, ymax=Inf, 
                                   fill="Highly unstable"), alpha=0.35) +
  geom_point(aes(time, cases, color="Cases")) +  
  geom_line(aes(time, final_infections, color="Finalized infections")) + 
  geom_line(aes(time, infections, color="Real-time naive estimate"), linetype=2) + 
  geom_point(aes(time, Average, color="Real-time sensor fusion"), shape=17) + 
  geom_rect(data=data.frame(), aes(xmin=df$time[i], xmax=df$time[i]+1, 
                                     ymin=rep(0,length(i)), ymax=df$kernel[i], 
                                     fill="Reporting delay"), 
            color="lightgray", alpha=0.35) +
  geom_vline(xintercept=mid_infect_date, color="darkgray", linetype="dotted") + 
  xlab("Date") + ylab("Cases/infections per 100,000 people") + 
  labs(title="Estimating COVID-19 infections in New York") + 
  scale_color_manual("", 
                     breaks = c("Cases", "Finalized infections", "Real-time naive estimate", "Real-time sensor fusion"),
                     values = c(case_color, final_infections_color, infections_color, average_nowcast_color),
                     guide = guide_legend(override.aes = list(linetype=c(NA, 1, 2, NA), shape=c(19,NA,NA,17)))) +
  scale_fill_manual("",
                    breaks = c("Reporting delay", "Highly unstable"),
                    values = c(kernel_color, unstable_color)) + 
  theme_bw() + theme(legend.position = "bottom") + guides(fill = "none") +
  theme(plot.margin=grid::unit(c(0,0,0,0), "mm"), 
        text=element_text(size=10, color="black"), #family="Bitstream Vera Sans"), 
        plot.title = element_text(hjust = 0.5, size=9, color="black"),
        axis.title.y = element_text(size=8), axis.title.x = element_text(size=8),
        axis.text.x=element_text(color='black'),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) + 
  scale_x_date(breaks = bimonthly, date_labels =  "%Y-%m-%d", expand = c(0, 0)) +
  coord_cartesian(ylim=c(0, max(df$cases)), expand = 0)

ggsave(file="nowcast_demo.pdf", width=8, height=3.75, dpi=300)
```